load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "text",
    srcs = ["text.cc"],
    hdrs = ["text.h"],
    visibility = [
        "//gateway/controller:__pkg__",
    ],
    deps = [
        "//:todo",
    ],
)
